// Business metadata constants for consistent options across the application

export const LAW_FIRM_OPTIONS = [
  { value: 'Akin & Gump', label: 'Akin & Gump' },
  { value: 'Allen & Overy', label: 'Allen & Overy' },
  { value: 'Arendt & Medernach SA', label: 'Arendt & Medernach SA' },
  { value: 'Arthur Cox', label: 'Arthur Cox' },
  { value: 'Ashurst', label: 'Ashurst' },
  { value: 'Balch & Bingham LLP', label: 'Balch & Bingham LLP' },
  { value: 'Bedrock Group', label: 'Bedrock Group' },
  { value: 'Buchalter', label: 'Buchalter' },
  { value: 'Carey Olsen Jersey', label: 'Carey Olsen Jersey' },
  { value: 'Choate', label: 'Choate' },
  { value: 'Cleary Gottlieb Steen & Hamilton LLP (CGSH)', label: 'Cleary Gottlieb Steen & Hamilton LLP (CGSH)' },
  { value: 'Clifford Chance', label: 'Clifford Chance' },
  { value: 'Cohnreznick', label: 'Cohnreznick' },
  { value: 'Columbia Pacific Law Firm LLC', label: 'Columbia Pacific Law Firm LLC' },
  { value: 'Cooley LLP', label: 'Cooley LLP' },
  { value: 'Cornerstone', label: 'Cornerstone' },
  { value: 'Croke Fairchild Duarte & Beres LLC', label: 'Croke Fairchild Duarte & Beres LLC' },
  { value: 'Davis Polk', label: 'Davis Polk' },
  { value: 'Debevoise & Plimpton', label: 'Debevoise & Plimpton' },
  { value: 'Dechert LLP', label: 'Dechert LLP' },
  { value: 'Dentons', label: 'Dentons' },
  { value: 'DLA Piper', label: 'DLA Piper' },
  { value: 'Doida Crow Legal', label: 'Doida Crow Legal' },
  { value: 'Faegre Drinker', label: 'Faegre Drinker' },
  { value: 'Foley & Lardner', label: 'Foley & Lardner' },
  { value: 'Fried Frank', label: 'Fried Frank' },
  { value: 'Gibson Dunn & Crutcher', label: 'Gibson Dunn & Crutcher' },
  { value: 'Goodwin Procter LLP', label: 'Goodwin Procter LLP' },
  { value: 'Greenberg Traurig, LLP (GTLaw)', label: 'Greenberg Traurig, LLP (GTLaw)' },
  { value: 'Gunderson Dettmer', label: 'Gunderson Dettmer' },
  { value: 'Haynes Boone', label: 'Haynes Boone' },
  { value: 'Holland & Hart', label: 'Holland & Hart' },
  { value: 'Holland & Knight', label: 'Holland & Knight' },
  { value: 'Ice Miller', label: 'Ice Miller' },
  { value: 'In house', label: 'In house' },
  { value: 'Investment Law Group', label: 'Investment Law Group' },
  { value: 'Jackson Walker LLP', label: 'Jackson Walker LLP' },
  { value: 'K&L Gates', label: 'K&L Gates' },
  { value: 'Kirkland & Ellis', label: 'Kirkland & Ellis' },
  { value: 'Kromann Reumert', label: 'Kromann Reumert' },
  { value: 'Latham & Watkins', label: 'Latham & Watkins' },
  { value: 'Loyens & Loeff', label: 'Loyens & Loeff' },
  { value: 'Mag Stone Law', label: 'Mag Stone Law' },
  { value: 'Mannheimer Swartling Advokatbyra AB', label: 'Mannheimer Swartling Advokatbyra AB' },
  { value: 'Mayer Brown', label: 'Mayer Brown' },
  { value: 'Maynard Cooper & Gale', label: 'Maynard Cooper & Gale' },
  { value: 'McDermott Will & Emery', label: 'McDermott Will & Emery' },
  { value: 'McGuire Woods', label: 'McGuire Woods' },
  { value: 'Miles and Stockbridge', label: 'Miles and Stockbridge' },
  { value: 'Mofo', label: 'Mofo' },
  { value: 'Morgan Lewis', label: 'Morgan Lewis' },
  { value: 'Morrison & Foerster LLP', label: 'Morrison & Foerster LLP' },
  { value: 'Morrison Cohen', label: 'Morrison Cohen' },
  { value: 'Mourant', label: 'Mourant' },
  { value: 'Neal, Gerber & Eisenberg', label: 'Neal, Gerber & Eisenberg' },
  { value: 'Ogier', label: 'Ogier' },
  { value: 'Orrick Herrington & Sutcliffe', label: 'Orrick Herrington & Sutcliffe' },
  { value: 'Osborne Clarke', label: 'Osborne Clarke' },
  { value: 'Paul Weiss', label: 'Paul Weiss' },
  { value: 'Perkins Coie', label: 'Perkins Coie' },
  { value: 'Plesner', label: 'Plesner' },
  { value: 'Proskauer Rose (UK) LLP', label: 'Proskauer Rose (UK) LLP' },
  { value: 'Proskauer Rose (US) LLP', label: 'Proskauer Rose (US) LLP' },
  { value: 'Pryor Cashman LLP', label: 'Pryor Cashman LLP' },
  { value: 'Purrington Moody Weil (PMW)', label: 'Purrington Moody Weil (PMW)' },
  { value: 'Reed Smith', label: 'Reed Smith' },
  { value: 'Reitler Kailas & Rosenblatt LLP (RKR)', label: 'Reitler Kailas & Rosenblatt LLP (RKR)' },
  { value: 'Ropes & Gray', label: 'Ropes & Gray' },
  { value: 'Sadis & Goldberg', label: 'Sadis & Goldberg' },
  { value: 'Schulte Roth & Zabel (SRZ)', label: 'Schulte Roth & Zabel (SRZ)' },
  { value: 'Shearman & Sterling', label: 'Shearman & Sterling' },
  { value: 'Sidley Austin LLP', label: 'Sidley Austin LLP' },
  { value: 'Simpson Thacher & Bartlett', label: 'Simpson Thacher & Bartlett' },
  { value: 'Simpson Thacher & Bartlett (UK)', label: 'Simpson Thacher & Bartlett (UK)' },
  { value: 'Simpson Thacher & Bartlett (US)', label: 'Simpson Thacher & Bartlett (US)' },
  { value: 'Skadden', label: 'Skadden' },
  { value: 'Taft Stettinius & Hollister', label: 'Taft Stettinius & Hollister' },
  { value: 'Troutman', label: 'Troutman' },
  { value: 'Vinson & Elkins LLP', label: 'Vinson & Elkins LLP' },
  { value: 'Weil, Gotshal & Manges LLP', label: 'Weil, Gotshal & Manges LLP' },
  { value: 'Wiggin LLP', label: 'Wiggin LLP' },
  { value: 'Willkie Farr', label: 'Willkie Farr' },
  { value: 'WilmerHale', label: 'WilmerHale' },
  { value: 'Wilson Sonsini Goodrich & Rosati', label: 'Wilson Sonsini Goodrich & Rosati' },
  { value: 'Winstead', label: 'Winstead' },
  { value: 'Winston & Strawn LLP', label: 'Winston & Strawn LLP' },
  { value: 'Withers LLP', label: 'Withers LLP' },
  { value: 'No Info', label: 'No Info' }
] as const

export const FUND_MANAGER_OPTIONS = [
  { value: '1818', label: '1818' },
  { value: '2150', label: '2150' },
  { value: '10 East', label: '10 East' },
  { value: '1982 Ventures', label: '1982 Ventures' },
  { value: '3L Capital', label: '3L Capital' },
  { value: '528Hz', label: '528Hz' },
  { value: '747 Capital', label: '747 Capital' },
  { value: '7wire Ventures', label: '7wire Ventures' },
  { value: '8VC', label: '8VC' },
  { value: 'ACA Group', label: 'ACA Group' },
  { value: 'Access Holdings', label: 'Access Holdings' },
  { value: 'Accolade Partners', label: 'Accolade Partners' },
  { value: 'Addition', label: 'Addition' },
  { value: 'Albacore Capital LLP', label: 'Albacore Capital LLP' },
  { value: 'Alvarez & Marsal Capital', label: 'Alvarez & Marsal Capital' },
  { value: 'Ambler Brook', label: 'Ambler Brook' },
  { value: 'American Industrial Partners', label: 'American Industrial Partners' },
  { value: 'American Securities LLC', label: 'American Securities LLC' },
  { value: 'AnaCap FP', label: 'AnaCap FP' },
  { value: 'Andreessen Horowitz', label: 'Andreessen Horowitz' },
  { value: 'Anson Funds', label: 'Anson Funds' },
  { value: 'Antler', label: 'Antler' },
  { value: 'Apogem Capital LLC', label: 'Apogem Capital LLC' },
  { value: 'Apollo Global Management', label: 'Apollo Global Management' },
  { value: 'Arbour Lane Capital Management', label: 'Arbour Lane Capital Management' },
  { value: 'Aristata', label: 'Aristata' },
  { value: 'Arlington Capital Partners', label: 'Arlington Capital Partners' },
  { value: 'Armanino LLP', label: 'Armanino LLP' },
  { value: 'Arrow Global Group', label: 'Arrow Global Group' },
  { value: 'Artemis Capital Partners', label: 'Artemis Capital Partners' },
  { value: 'Artes Capital', label: 'Artes Capital' },
  { value: 'Artis Ventures', label: 'Artis Ventures' },
  { value: 'Aspirity Partners', label: 'Aspirity Partners' },
  { value: 'Astanor Ventures', label: 'Astanor Ventures' },
  { value: 'Asymmetric Capital Partners', label: 'Asymmetric Capital Partners' },
  { value: 'Atlas Holdings', label: 'Atlas Holdings' },
  { value: 'Atypical Partner', label: 'Atypical Partner' },
  { value: 'Audax Group', label: 'Audax Group' },
  { value: 'Autumn Lane Advisors', label: 'Autumn Lane Advisors' },
  { value: 'Axcel', label: 'Axcel' },
  { value: 'Axxes', label: 'Axxes' },
  { value: 'Bain & Company', label: 'Bain & Company' },
  { value: 'Bain Capital', label: 'Bain Capital' },
  { value: 'Ballistic Ventures', label: 'Ballistic Ventures' },
  { value: 'Baobab', label: 'Baobab' },
  { value: 'Base Case Capital', label: 'Base Case Capital' },
  { value: 'Bayswater', label: 'Bayswater' },
  { value: 'Becker 8 LLC', label: 'Becker 8 LLC' },
  { value: 'Bencis Capital Partners BV', label: 'Bencis Capital Partners BV' },
  { value: 'Bessemer Venture Partners', label: 'Bessemer Venture Partners' },
  { value: 'Biospring Partners', label: 'Biospring Partners' },
  { value: 'Blackbird', label: 'Blackbird' },
  { value: 'Blackstone Group', label: 'Blackstone Group' },
  { value: 'Blossom Capital', label: 'Blossom Capital' },
  { value: 'Blue Owl Capital', label: 'Blue Owl Capital' },
  { value: 'Blue Torch Capital', label: 'Blue Torch Capital' },
  { value: 'BlueArc Capital', label: 'BlueArc Capital' },
  { value: 'BOND Capital', label: 'BOND Capital' },
  { value: 'Brighton Park Capital Management LLC', label: 'Brighton Park Capital Management LLC' },
  { value: 'Broadcrest', label: 'Broadcrest' },
  { value: 'BV Investment Partners', label: 'BV Investment Partners' },
  { value: 'Caduceus Capital Partners', label: 'Caduceus Capital Partners' },
  { value: 'Calm Company Fund', label: 'Calm Company Fund' },
  { value: 'CAP91', label: 'CAP91' },
  { value: 'Capital Dynamics', label: 'Capital Dynamics' },
  { value: 'CapMan', label: 'CapMan' },
  { value: 'CapVest', label: 'CapVest' },
  { value: 'Carlyle Group', label: 'Carlyle Group' },
  { value: 'Causeway Equity Partners LLC', label: 'Causeway Equity Partners LLC' },
  { value: 'CCP Operating, LLC', label: 'CCP Operating, LLC' },
  { value: 'Centerbridge Partners', label: 'Centerbridge Partners' },
  { value: 'Cerberus Capital Management', label: 'Cerberus Capital Management' },
  { value: 'Chalfen Ventures', label: 'Chalfen Ventures' },
  { value: 'Clarion Capital Partners', label: 'Clarion Capital Partners' },
  { value: 'Clarion Partners', label: 'Clarion Partners' },
  { value: 'Clayton, Dubilier & Rice', label: 'Clayton, Dubilier & Rice' },
  { value: 'Clearlake Capital Group LP', label: 'Clearlake Capital Group LP' },
  { value: 'Cohesive Capital Partners', label: 'Cohesive Capital Partners' },
  { value: 'Collaborative Fund', label: 'Collaborative Fund' },
  { value: 'Collective Rights', label: 'Collective Rights' },
  { value: 'Coller Capital', label: 'Coller Capital' },
  { value: 'Columbia Pacific Wealth Management', label: 'Columbia Pacific Wealth Management' },
  { value: 'Commonfund Private Equity', label: 'Commonfund Private Equity' },
  { value: 'Composition Capital', label: 'Composition Capital' },
  { value: 'Compound Capital Holdings, LLC', label: 'Compound Capital Holdings, LLC' },
  { value: 'Connect Ventures', label: 'Connect Ventures' },
  { value: 'Cornerstone PE', label: 'Cornerstone PE' },
  { value: 'Council Oaks Partners, LLC', label: 'Council Oaks Partners, LLC' },
  { value: 'CRE Venture Capital', label: 'CRE Venture Capital' },
  { value: 'Creador', label: 'Creador' },
  { value: 'Crestview Partners', label: 'Crestview Partners' },
  { value: 'Crow Holdings Capital Partners, L.L.C.', label: 'Crow Holdings Capital Partners, L.L.C.' },
  { value: 'CVC Group', label: 'CVC Group' },
  { value: 'CVC Secondary Partners', label: 'CVC Secondary Partners' },
  { value: 'Dauntless Capital Partners', label: 'Dauntless Capital Partners' },
  { value: 'Dechert', label: 'Dechert' },
  { value: 'Definition Capital', label: 'Definition Capital' },
  { value: 'Derby Copeland Capital', label: 'Derby Copeland Capital' },
  { value: 'DIG Ventures', label: 'DIG Ventures' },
  { value: 'Dimension Capital', label: 'Dimension Capital' },
  { value: 'Dorchester Capital Advisors', label: 'Dorchester Capital Advisors' },
  { value: 'Drive Capital, LLC', label: 'Drive Capital, LLC' },
  { value: 'Eagle Rock Properties', label: 'Eagle Rock Properties' },
  { value: 'EagleTree', label: 'EagleTree' },
  { value: 'Eastward Capital Partners', label: 'Eastward Capital Partners' },
  { value: 'EIV Capital', label: 'EIV Capital' },
  { value: 'EJF Capital LLC', label: 'EJF Capital LLC' },
  { value: 'EMK Capital', label: 'EMK Capital' },
  { value: 'Endicott Capital Management, L.L.C.', label: 'Endicott Capital Management, L.L.C.' },
  { value: 'Envision Life Labs LLC', label: 'Envision Life Labs LLC' },
  { value: 'EQT Group', label: 'EQT Group' },
  { value: 'EQUIAM', label: 'EQUIAM' },
  { value: 'Eventide Asset Management Inc.', label: 'Eventide Asset Management Inc.' },
  { value: 'Everside Capital Partners', label: 'Everside Capital Partners' },
  { value: 'Fifth Wall', label: 'Fifth Wall' },
  { value: 'Fin Capital', label: 'Fin Capital' },
  { value: 'Foothill Ventures', label: 'Foothill Ventures' },
  { value: 'Fortress Investment Group', label: 'Fortress Investment Group' },
  { value: 'FPV Ventures', label: 'FPV Ventures' },
  { value: 'Fulcrum Equity Partners', label: 'Fulcrum Equity Partners' },
  { value: 'FUSE', label: 'FUSE' },
  { value: 'G2 Venture Partners LLC', label: 'G2 Venture Partners LLC' },
  { value: 'Gauge Capital LLC', label: 'Gauge Capital LLC' },
  { value: 'GEC Partners', label: 'GEC Partners' },
  { value: 'General Atlantic', label: 'General Atlantic' },
  { value: 'Gerber/Taylor Management', label: 'Gerber/Taylor Management' },
  { value: 'GI Partners Acquisitions LLC', label: 'GI Partners Acquisitions LLC' },
  { value: 'Global Health Investment Fund (GHIC)', label: 'Global Health Investment Fund (GHIC)' },
  { value: 'Global Infrastructure Partners', label: 'Global Infrastructure Partners' },
  { value: 'Global Ventures LLC', label: 'Global Ventures LLC' },
  { value: 'Graham Partners', label: 'Graham Partners' },
  { value: 'Grain Management', label: 'Grain Management' },
  { value: 'Great Hill Partners', label: 'Great Hill Partners' },
  { value: 'Great Point Partners', label: 'Great Point Partners' },
  { value: 'Greenoaks Capital', label: 'Greenoaks Capital' },
  { value: 'Gridiron Capital', label: 'Gridiron Capital' },
  { value: 'Group 11', label: 'Group 11' },
  { value: 'GrowthCurve Capital', label: 'GrowthCurve Capital' },
  { value: 'Guardian Capital Partners', label: 'Guardian Capital Partners' },
  { value: 'Hamilton Lane', label: 'Hamilton Lane' },
  { value: 'Harlan Capital Partners LLC', label: 'Harlan Capital Partners LLC' },
  { value: 'Harvest Partners', label: 'Harvest Partners' },
  { value: 'Haveli Investments', label: 'Haveli Investments' },
  { value: 'Haymaker Capital', label: 'Haymaker Capital' },
  { value: 'HCG Funds', label: 'HCG Funds' },
  { value: 'Hellman & Friedman LLC', label: 'Hellman & Friedman LLC' },
  { value: 'HFL', label: 'HFL' },
  { value: 'Hg Pooled Management Limited', label: 'Hg Pooled Management Limited' },
  { value: 'HighVista Strategies LLC', label: 'HighVista Strategies LLC' },
  { value: 'Hillhouse Investment', label: 'Hillhouse Investment' },
  { value: 'Hilltop Capital Partners LLC', label: 'Hilltop Capital Partners LLC' },
  { value: 'Hines', label: 'Hines' },
  { value: 'Hollyport Capital', label: 'Hollyport Capital' },
  { value: 'HQ Capital', label: 'HQ Capital' },
  { value: 'HQ Digital (Digital Currency Group)', label: 'HQ Digital (Digital Currency Group)' },
  { value: 'Hughes & Company', label: 'Hughes & Company' },
  { value: 'Humbition', label: 'Humbition' },
  { value: 'I Squared Capital', label: 'I Squared Capital' },
  { value: 'Index Ventures', label: 'Index Ventures' },
  { value: 'Integrum Capital', label: 'Integrum Capital' },
  { value: 'J.C. Flowers & Co. LLC', label: 'J.C. Flowers & Co. LLC' },
  { value: 'Jackson Square Partners LLC', label: 'Jackson Square Partners LLC' },
  { value: 'Jasper Ridge Services, LLC', label: 'Jasper Ridge Services, LLC' },
  { value: 'JMI Equity', label: 'JMI Equity' },
  { value: 'Jumpstart Foundry', label: 'Jumpstart Foundry' },
  { value: 'Keensight Capital', label: 'Keensight Capital' },
  { value: 'Kelso & Company', label: 'Kelso & Company' },
  { value: 'Kimmeridge', label: 'Kimmeridge' },
  { value: 'Kleiner Perkins', label: 'Kleiner Perkins' },
  { value: 'KMD Investments', label: 'KMD Investments' },
  { value: 'Kohlberg & Company', label: 'Kohlberg & Company' },
  { value: 'Kohlberg Kravis Roberts & Co. (KKR)', label: 'Kohlberg Kravis Roberts & Co. (KKR)' },
  { value: 'KSL Capital Partners', label: 'KSL Capital Partners' },
  { value: 'KSV Global', label: 'KSV Global' },
  { value: 'L Capital LLC', label: 'L Capital LLC' },
  { value: 'Lattice Capital', label: 'Lattice Capital' },
  { value: 'LCN Capital Partners LP', label: 'LCN Capital Partners LP' },
  { value: 'Lexington Partners', label: 'Lexington Partners' },
  { value: 'Linse Capital', label: 'Linse Capital' },
  { value: 'Locust Point Capital, Inc', label: 'Locust Point Capital, Inc' },
  { value: 'Long Path Partners', label: 'Long Path Partners' },
  { value: 'Longwater Opportunities', label: 'Longwater Opportunities' },
  { value: 'LS Power Development, LLC', label: 'LS Power Development, LLC' },
  { value: 'Madison International Realty', label: 'Madison International Realty' },
  { value: 'Madrona Venture Group', label: 'Madrona Venture Group' },
  { value: 'Maple Park Capital Partners Management, LP', label: 'Maple Park Capital Partners Management, LP' },
  { value: 'Marathon Asset Management', label: 'Marathon Asset Management' },
  { value: 'Maroon Invest Global', label: 'Maroon Invest Global' },
  { value: 'Matter Venture Partners', label: 'Matter Venture Partners' },
  { value: 'MeetPerry', label: 'MeetPerry' },
  { value: 'Melange Capital', label: 'Melange Capital' },
  { value: 'Mesirow Financial', label: 'Mesirow Financial' },
  { value: 'Metropolitan Partners Group', label: 'Metropolitan Partners Group' },
  { value: 'Monarch Investment Partners Management, LLC', label: 'Monarch Investment Partners Management, LLC' },
  { value: 'Monomoy Capital Management, L.P', label: 'Monomoy Capital Management, L.P' },
  { value: 'Monroe Capital LLC', label: 'Monroe Capital LLC' },
  { value: 'Moonfire Ventures', label: 'Moonfire Ventures' },
  { value: 'NaviMed Capital', label: 'NaviMed Capital' },
  { value: 'Neon', label: 'Neon' },
  { value: 'Neuberger Berman', label: 'Neuberger Berman' },
  { value: 'New 2nd Capital', label: 'New 2nd Capital' },
  { value: 'New Enterprise Associates', label: 'New Enterprise Associates' },
  { value: 'New MainStream Capital', label: 'New MainStream Capital' },
  { value: 'New Mountain Capital, LLC', label: 'New Mountain Capital, LLC' },
  { value: 'Newpath Partners', label: 'Newpath Partners' },
  { value: 'NewRoad Capital Partners', label: 'NewRoad Capital Partners' },
  { value: 'NewVest Management, LP', label: 'NewVest Management, LP' },
  { value: 'Next Play Capital', label: 'Next Play Capital' },
  { value: 'Nordic Capital', label: 'Nordic Capital' },
  { value: 'Nordic Investment Opportunities', label: 'Nordic Investment Opportunities' },
  { value: 'Nordstar', label: 'Nordstar' },
  { value: 'Noteus', label: 'Noteus' },
  { value: 'NXSTEP', label: 'NXSTEP' },
  { value: 'Oak Hill Capital', label: 'Oak Hill Capital' },
  { value: 'Oakley Capital', label: 'Oakley Capital' },
  { value: 'OIC', label: 'OIC' },
  { value: 'Old Hickory Partners', label: 'Old Hickory Partners' },
  { value: 'One Peak Partners', label: 'One Peak Partners' },
  { value: 'OneVentures', label: 'OneVentures' },
  { value: 'Onex Corp', label: 'Onex Corp' },
  { value: 'Opto Investments', label: 'Opto Investments' },
  { value: 'Orchard Investment Partners', label: 'Orchard Investment Partners' },
  { value: 'Outsiders', label: 'Outsiders' },
  { value: 'Pacific Lake Partners', label: 'Pacific Lake Partners' },
  { value: 'PAG', label: 'PAG' },
  { value: 'Palladium Equity Partners, LLC', label: 'Palladium Equity Partners, LLC' },
  { value: 'ParaFi Capital', label: 'ParaFi Capital' },
  { value: 'PartnersAdmin LLC', label: 'PartnersAdmin LLC' },
  { value: 'Paul Weiss', label: 'Paul Weiss' },
  { value: 'PC2 Capital', label: 'PC2 Capital' },
  { value: 'Peak XV Partners Operations LLC', label: 'Peak XV Partners Operations LLC' },
  { value: 'Penny Jar Capital', label: 'Penny Jar Capital' },
  { value: 'PGIM Real Estate', label: 'PGIM Real Estate' },
  { value: 'Phoenix Court', label: 'Phoenix Court' },
  { value: 'Pine Valley Capital Partners LLC', label: 'Pine Valley Capital Partners LLC' },
  { value: 'Platinum Equity', label: 'Platinum Equity' },
  { value: 'Pomona Capital', label: 'Pomona Capital' },
  { value: 'Portfolio Advisors', label: 'Portfolio Advisors' },
  { value: 'Potential Capital', label: 'Potential Capital' },
  { value: 'Praxis Ventures', label: 'Praxis Ventures' },
  { value: 'PrideCo Capital Partners', label: 'PrideCo Capital Partners' },
  { value: 'Primary Venture Partners', label: 'Primary Venture Partners' },
  { value: 'Principal Financial Group', label: 'Principal Financial Group' },
  { value: 'Proskauer Rose LLP', label: 'Proskauer Rose LLP' },
  { value: 'Proterra Investment Partners', label: 'Proterra Investment Partners' },
  { value: 'PSG Equity L.L.C.', label: 'PSG Equity L.L.C.' },
  { value: 'Quad-C', label: 'Quad-C' },
  { value: 'Quantum Energy Partners (2020), LLC', label: 'Quantum Energy Partners (2020), LLC' },
  { value: 'Raga Partners', label: 'Raga Partners' },
  { value: 'Recharge Capital', label: 'Recharge Capital' },
  { value: 'Recognize', label: 'Recognize' },
  { value: 'Recurring Capital Partners', label: 'Recurring Capital Partners' },
  { value: 'Renovo Capital', label: 'Renovo Capital' },
  { value: 'Restive', label: 'Restive' },
  { value: 'Resurgens Technology Advisors, L.P.', label: 'Resurgens Technology Advisors, L.P.' },
  { value: 'Revelstoke Capital Partners LLC', label: 'Revelstoke Capital Partners LLC' },
  { value: 'Rialto Capital', label: 'Rialto Capital' },
  { value: 'Rivean Capital', label: 'Rivean Capital' },
  { value: 'Riverwood Capital', label: 'Riverwood Capital' },
  { value: 'Roark Capital', label: 'Roark Capital' },
  { value: 'Rockpoint Group', label: 'Rockpoint Group' },
  { value: 'Rothschild', label: 'Rothschild' },
  { value: 'Rule 1 Ventures', label: 'Rule 1 Ventures' },
  { value: 'Sageview Capital', label: 'Sageview Capital' },
  { value: 'Satori Capital', label: 'Satori Capital' },
  { value: 'Savory Fund', label: 'Savory Fund' },
  { value: 'Second Alpha', label: 'Second Alpha' },
  { value: 'Section 32', label: 'Section 32' },
  { value: 'Section Partners', label: 'Section Partners' },
  { value: 'Sequoia Capital', label: 'Sequoia Capital' },
  { value: 'Sequoia Heritage', label: 'Sequoia Heritage' },
  { value: 'Silver Hill Energy Partners', label: 'Silver Hill Energy Partners' },
  { value: 'Silver Lake', label: 'Silver Lake' },
  { value: 'Silver Point Capital', label: 'Silver Point Capital' },
  { value: 'Singular Capital Partners', label: 'Singular Capital Partners' },
  { value: 'Sixth Street', label: 'Sixth Street' },
  { value: 'Sole Source Capital LLC', label: 'Sole Source Capital LLC' },
  { value: 'Solum Capital', label: 'Solum Capital' },
  { value: 'Sonoma Brands Capital', label: 'Sonoma Brands Capital' },
  { value: 'Spicewood Mineral Partners', label: 'Spicewood Mineral Partners' },
  { value: 'Sprints Capital Management Ltd', label: 'Sprints Capital Management Ltd' },
  { value: 'Standish', label: 'Standish' },
  { value: 'STB Partners Fund', label: 'STB Partners Fund' },
  { value: 'Sterling Investment Partners', label: 'Sterling Investment Partners' },
  { value: 'Stillmark', label: 'Stillmark' },
  { value: 'Stokes Stevenson', label: 'Stokes Stevenson' },
  { value: 'Stone Point Capital', label: 'Stone Point Capital' },
  { value: 'Stone Ridge', label: 'Stone Ridge' },
  { value: 'Stripes', label: 'Stripes' },
  { value: 'Sukna Ventures', label: 'Sukna Ventures' },
  { value: 'Tailwind Management LP', label: 'Tailwind Management LP' },
  { value: 'Ten Coves Capital', label: 'Ten Coves Capital' },
  { value: 'Tenzing', label: 'Tenzing' },
  { value: 'The Artemis Fund', label: 'The Artemis Fund' },
  { value: 'The Bascom Group', label: 'The Bascom Group' },
  { value: 'The Jordan Company', label: 'The Jordan Company' },
  { value: 'Thomas H. Lee Partners', label: 'Thomas H. Lee Partners' },
  { value: 'Thorofare Capital Inc', label: 'Thorofare Capital Inc' },
  { value: 'TIFF', label: 'TIFF' },
  { value: 'Timber Bay Partners', label: 'Timber Bay Partners' },
  { value: 'Tinicum Incorporated', label: 'Tinicum Incorporated' },
  { value: 'TOP Venture', label: 'TOP Venture' },
  { value: 'Touch Capital', label: 'Touch Capital' },
  { value: 'TowerBrook', label: 'TowerBrook' },
  { value: 'TPA', label: 'TPA' },
  { value: 'TPG', label: 'TPG' },
  { value: 'Tribe Capital Partners', label: 'Tribe Capital Partners' },
  { value: 'TrueBridge Capital Partners', label: 'TrueBridge Capital Partners' },
  { value: 'Truewind', label: 'Truewind' },
  { value: 'Turn/River Management L.P.', label: 'Turn/River Management L.P.' },
  { value: 'Uncommon Denominator', label: 'Uncommon Denominator' },
  { value: 'Upward Leader', label: 'Upward Leader' },
  { value: 'Urban Partners', label: 'Urban Partners' },
  { value: 'Valeas Capital Partners', label: 'Valeas Capital Partners' },
  { value: 'Valor Capital Group', label: 'Valor Capital Group' },
  { value: 'Valor Equity Partners', label: 'Valor Equity Partners' },
  { value: 'venBio', label: 'venBio' },
  { value: 'Ventures Platform', label: 'Ventures Platform' },
  { value: 'VentureSouq', label: 'VentureSouq' },
  { value: 'VGC Partners LLP', label: 'VGC Partners LLP' },
  { value: 'Vinyl', label: 'Vinyl' },
  { value: 'VMG Partners', label: 'VMG Partners' },
  { value: 'Voss Capital', label: 'Voss Capital' },
  { value: 'VSS Capital Partners', label: 'VSS Capital Partners' },
  { value: 'Vulcan Value Partners', label: 'Vulcan Value Partners' },
  { value: 'W Capital Partners', label: 'W Capital Partners' },
  { value: 'Weatherford Capital Management LLC', label: 'Weatherford Capital Management LLC' },
  { value: 'Wellspring Capital Management Group LLC', label: 'Wellspring Capital Management Group LLC' },
  { value: 'WestCap', label: 'WestCap' },
  { value: 'Westport Capital Partners', label: 'Westport Capital Partners' },
  { value: 'WM Partners', label: 'WM Partners' },
  { value: 'WovenEarth Ventures', label: 'WovenEarth Ventures' },
  { value: 'Wynnchurch', label: 'Wynnchurch' }
] as const

export const FUND_ADMIN_OPTIONS = [
  { value: '4Pines Fund Services', label: '4Pines Fund Services' },
  { value: 'Aduro', label: 'Aduro' },
  { value: 'Alpha Alternatives', label: 'Alpha Alternatives' },
  { value: 'Alter Domus', label: 'Alter Domus' },
  { value: 'Altum', label: 'Altum' },
  { value: 'Andrea Brown', label: 'Andrea Brown' },
  { value: 'Apex', label: 'Apex' },
  { value: 'Atlas', label: 'Atlas' },
  { value: 'Aztec Group', label: 'Aztec Group' },
  { value: 'Barrier Crest', label: 'Barrier Crest' },
  { value: 'Belasko', label: 'Belasko' },
  { value: 'BNP Paribas Securities Services', label: 'BNP Paribas Securities Services' },
  { value: 'BNY Mellon', label: 'BNY Mellon' },
  { value: 'CACEIS', label: 'CACEIS' },
  { value: 'Carta', label: 'Carta' },
  { value: 'Centaur Fund Services', label: 'Centaur Fund Services' },
  { value: 'CITCO', label: 'CITCO' },
  { value: 'Columbia Pacific Law Firm LLC', label: 'Columbia Pacific Law Firm LLC' },
  { value: 'Conner', label: 'Conner' },
  { value: 'Cornerstone', label: 'Cornerstone' },
  { value: 'Dominion', label: 'Dominion' },
  { value: 'EFG', label: 'EFG' },
  { value: 'European Fund Administration', label: 'European Fund Administration' },
  { value: 'Fairway', label: 'Fairway' },
  { value: 'FIS', label: 'FIS' },
  { value: 'Formidian', label: 'Formidian' },
  { value: 'Gen II', label: 'Gen II' },
  { value: 'GP Fund Solutions (GPFS)', label: 'GP Fund Solutions (GPFS)' },
  { value: 'HFL', label: 'HFL' },
  { value: 'HSBC Securities Services', label: 'HSBC Securities Services' },
  { value: 'In-house', label: 'In-house' },
  { value: 'Intertrust Group B.V', label: 'Intertrust Group B.V' },
  { value: 'INTREAL', label: 'INTREAL' },
  { value: 'IQ-EQ', label: 'IQ-EQ' },
  { value: 'JP Morgan', label: 'JP Morgan' },
  { value: 'JTC Fund Services', label: 'JTC Fund Services' },
  { value: 'Langham Hall', label: 'Langham Hall' },
  { value: 'Liccar Fund Services', label: 'Liccar Fund Services' },
  { value: 'Maitland', label: 'Maitland' },
  { value: 'Maples', label: 'Maples' },
  { value: 'Meritage', label: 'Meritage' },
  { value: 'MG Stover', label: 'MG Stover' },
  { value: 'Morgan Stanley', label: 'Morgan Stanley' },
  { value: 'Northern Trust', label: 'Northern Trust' },
  { value: 'NREP', label: 'NREP' },
  { value: 'Ocorian', label: 'Ocorian' },
  { value: 'Partners Admin', label: 'Partners Admin' },
  { value: 'Permian', label: 'Permian' },
  { value: 'Pictet Fund Administration', label: 'Pictet Fund Administration' },
  { value: 'RBC Investor & Treasury Services', label: 'RBC Investor & Treasury Services' },
  { value: 'Sanne Group', label: 'Sanne Group' },
  { value: 'SEI', label: 'SEI' },
  { value: 'Société Générale Securities Services', label: 'Société Générale Securities Services' },
  { value: 'SS&C', label: 'SS&C' },
  { value: 'Standish', label: 'Standish' },
  { value: 'State Street', label: 'State Street' },
  { value: 'Strata', label: 'Strata' },
  { value: 'Swiss Financial Services', label: 'Swiss Financial Services' },
  { value: 'Theorem', label: 'Theorem' },
  { value: 'TMF Group', label: 'TMF Group' },
  { value: 'Tower', label: 'Tower' },
  { value: 'Trustmoore', label: 'Trustmoore' },
  { value: 'Ultimus LeverPoint', label: 'Ultimus LeverPoint' },
  { value: 'UMB', label: 'UMB' },
  { value: 'Venture Back Office', label: 'Venture Back Office' },
  { value: 'XFO', label: 'XFO' },
  { value: 'No Info', label: 'No Info' }
] as const

export const JURISDICTION_OPTIONS = [
  { value: 'Alberta, Canada', label: 'Alberta, Canada' },
  { value: 'Bermuda', label: 'Bermuda' },
  { value: 'British Virgin Islands (BVI)', label: 'British Virgin Islands (BVI)' },
  { value: 'Cayman Islands', label: 'Cayman Islands' },
  { value: 'Delaware', label: 'Delaware' },
  { value: 'Denmark', label: 'Denmark' },
  { value: 'England', label: 'England' },
  { value: 'Finland', label: 'Finland' },
  { value: 'France', label: 'France' },
  { value: 'Germany', label: 'Germany' },
  { value: 'Guernsey', label: 'Guernsey' },
  { value: 'Ireland', label: 'Ireland' },
  { value: 'Jersey', label: 'Jersey' },
  { value: 'Luxembourg', label: 'Luxembourg' },
  { value: 'Mauritius', label: 'Mauritius' },
  { value: 'Netherlands', label: 'Netherlands' },
  { value: 'New South Wales', label: 'New South Wales' },
  { value: 'Province of Ontario, Canada', label: 'Province of Ontario, Canada' },
  { value: 'Scotland', label: 'Scotland' },
  { value: 'State of New York', label: 'State of New York' },
  { value: 'No Info', label: 'No Info' }
] as const

// Type exports for TypeScript
export type LawFirmOption = typeof LAW_FIRM_OPTIONS[number]['value']
export type FundManagerOption = typeof FUND_MANAGER_OPTIONS[number]['value']
export type FundAdminOption = typeof FUND_ADMIN_OPTIONS[number]['value']
export type JurisdictionOption = typeof JURISDICTION_OPTIONS[number]['value']

// Default values (empty means user hasn't made a choice yet)
export const DEFAULT_METADATA = {
  law_firm: '' as LawFirmOption | '',
  fund_manager: '' as FundManagerOption | '',
  fund_admin: '' as FundAdminOption | '',
  jurisdiction: '' as JurisdictionOption | ''
}
